# Generated by Django 4.1 on 2022-12-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('occupation', models.CharField(max_length=25, verbose_name='Occupation')),
                ('salary', models.IntegerField()),
                ('gender', models.CharField(max_length=25, verbose_name='Gender')),
            ],
        ),
    ]
