# Generated by Django 4.1 on 2023-01-02 04:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=25, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='assets',
            field=models.CharField(default=223, max_length=25, verbose_name='Assets'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='city',
            field=models.CharField(default=2, max_length=25, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone',
            field=models.CharField(default=34, max_length=25, verbose_name='Phone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='revenue',
            field=models.CharField(default=44, max_length=25, verbose_name='Revenue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='school',
            field=models.CharField(default=55, max_length=25, verbose_name='School'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='tenor',
            field=models.CharField(default=44, max_length=25, verbose_name='Tenor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='town',
            field=models.CharField(default=55, max_length=25, verbose_name='Town'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='zipcode',
            field=models.CharField(default=66, max_length=25, verbose_name='Zip Code'),
            preserve_default=False,
        ),
    ]
