# Generated by Django 4.1 on 2023-01-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_remove_vendor_address_remove_vendor_assets_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MRMmodels',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('rating', models.EmailField(max_length=200, verbose_name='Rating')),
                ('lob', models.CharField(max_length=25, verbose_name='LOB')),
            ],
        ),
    ]
